fix: reduced chunk size in chunking algorithms by 12 bytes
animo/react-native-ble-didcomm pull request #32
Opened 2023-03-15 11:09 UTC by rapaktech

2023-03-15 11:30 UTC, TimoGlastra requested changes

2023-03-15 11:32 UTC, rapaktech commented on android/src/main/java/com/reactnativebledidcomm/central/CentralManager.kt
> +            val chunkSize = min(connectedMtu - 12, message.count())
Yep. Makes sense. On it!

2023-03-15 12:51 UTC, rapaktech commented
@blu3beri I think I got it right for `android`, but I don't know for `ios`, and I have no way to test it

2023-03-15 13:30 UTC, blu3beri approved these changes
It looks good to me, but it must be tested before it is released. You can you use the example app inside the library if needed.

I think if long as it compiles it is okay for iOS.

2023-03-15 13:32 UTC, blu3beri commented
Some older iOS devices support 20 bytes transport as default. I highly doubt this will cause any issues here, but moving that to 8 bytes is a tad bit low. This comment is more of a note, for potential issues in the future.

2023-03-15 13:35 UTC, rapaktech commented
I'm setting up testing for android now. I will need help testing ios. @morrieinmaas can you help test cross-platform and iOS-iOS?

2023-03-15 13:41 UTC, morrieinmaas commented
> @blu3beri I think I got it right for `android`, but I don't know for `ios`, and I have no way to test it

I can test this tomorrow with iOS <-> Android and iOS <-> iOS if no one else does meanwhile

2023-03-15 13:42 UTC, morrieinmaas commented
Nice one @rapaktech! 🤞 this also just works on ios

2023-03-15 14:27 UTC, rapaktech commented
Android builds and android-android works bidirectionally
<img width="844" alt="Screenshot 2023-03-15 at 3 25 09 PM" src="https://user-images.githubusercontent.com/54069719/225339942-55318830-c354-4704-bc12-11ea27c66116.png">
<img width="844" alt="Screenshot 2023-03-15 at 3 25 30 PM" src="https://user-images.githubusercontent.com/54069719/225340084-4a2560bf-bea6-4de8-962c-658838571930.png">

2023-03-15 23:19 UTC, TimoGlastra approved these changes

2023-03-16 07:27 UTC, merged

2023-03-16 08:55 UTC, rapaktech commented
Woohoo!

2023-03-16 12:47 UTC, morrieinmaas commented
iOS <-> iOS worx

2023-03-16 14:20 UTC, morrieinmaas commented
iOS<->Android works both ways