feat: added expo plugin
animo/react-native-ble-didcomm pull request #36
Opened 2023-03-28 12:56 UTC by janrtvld

2023-03-28 13:01 UTC, morrieinmaas requested changes
What about iOS?

2023-03-29 06:53 UTC, janrtvld commented on app.plugin.js
> +module.exports = require('./build/withAndroidPermissions.js')
It is exported from the build folder.

2023-03-29 06:54 UTC, janrtvld commented
> What about iOS?

IOS doesn't require any additional config (according to the README).

2023-03-29 07:04 UTC, morrieinmaas commented on app.plugin.js
> +module.exports = require('./build/withAndroidPermissions.js')
ah yeah true

2023-03-29 07:14 UTC, blu3beri approved these changes
Looks good! As long as it's tested with an expo app I think we can merge it and release it.

2023-03-29 07:14 UTC, blu3beri commented on package.json
> +    "@expo/config-plugins": "^6.0.1",
Can this not be a dev dependency?

2023-03-29 13:35 UTC, morrieinmaas approved these changes

2023-03-29 13:38 UTC, merged